export const qaTags = {
    accordion: 'accordion',
    banner: 'banner',
    btn: 'btn',
    btnClose: 'btn-close',
    btnNextTo: 'btn-next-to',
    btnBackTo: 'btn-back-to',
    btnCloseModal: 'btn-close-modal',
    btnShowDropdown: 'btn-show-dropdown',
    card: 'card',
    carousel: 'carousel',
    carouselSlideItem: (index: number): string => `carousel-slide-${index}`,
    counter: 'counter',
    counterContent: 'counter-content',
    titleCurrentMonth: 'title-current-month',
    titleCurrentYear: 'title-current-year',
    blockDayItem: (day: number | null): string => `block-day-${day}`,
    datepicker: 'datepicker',
    dropdownList: 'dropdown-list ',
    dropdownItem: (index: number): string => `dropdown-item-${index}`,
    checkbox: 'checkbox',
    checkboxLabel: 'checkbox-label',
    radioBtn: 'radio-btn',
    radioBtnLabel: 'radio-btn-label',
    input: 'input',
    inputLabelError: 'input-label-error',
    inputCaption: 'input-caption ',
    textarea: 'textarea',
    label: 'label',
    list: 'list',
    listItem: (index: number): string => `list-item-${index}`,
    listItemMainTitle: 'list-item-main-title',
    listItemSecondTitle: 'list-item-second-title',
    loader: 'loader',
    modal: 'modal',
    titleModalName: 'title-modal-name',
    blockModalDescription: 'block-modal-description',
    pagination: 'pagination',
    paginationItemSelected: 'pagination-item-selected',
    searchInput: 'search-input',
    segmentControl: 'segment-control',
    segmentControlItem: (index: number): string => `segment-control-item-${index}`,
    snackbar: 'snackbar',
    snackbarBtn: 'snackbar-btn',
    tabs: 'tabs',
    tabsItem: (index: number): string => `tabs-item-${index}`,
    tabsItemSelected: 'tabs-item-selected',
    tabsItemContent: 'tabs-item-content ',
    tooltip: 'tooltip',
    blockDescription: 'block-description',
    uploadInput: 'upload-input',
    picture: 'picture',
};
